### ISSUE TITLE
Message ordering and safety

### ISSUE THREAD

**Issue by AblEdge** [crisrise/vmq_kafka#1]
Hello @crisrise
I'm working on a project in which message ordering and safety (not to lose or miss any message) must be guarantee.
Does ```vmq_kafka``` support message ordering and safety?
What if ```vmq_kafka``` not be able to produce the message in situations like Kafka server failure, network issues, or internal error in ```vmq_kafka```?
Does it roll back/revert failed messages to ```Vernemq``` or messages might be lost?

**Comment by crisrise** [comment]
Hi @AblEdge brod component, the library used as kafka client, supports automatic reconnection in case the kafka cluster is not available for some reasons. In case the kafka connection is not available the message might be lost.

Can exaplain a bit which kind of functionality you need around ordering ?
With safety do you mean not loosing any message due to kafka cluster failures?

**Comment by AblEdge** [comment]
> Can exaplain a bit which kind of functionality you need around ordering ?

By ordering I mean forward messages to Kafka exactly in the same order they have received by VerneMq, with no duplication and displacement of messages (```exactly-once``` delivery guarantee to Kafka).

> With safety do you mean not loosing any message due to kafka cluster failures?

Yes, event due to vmq_kafka failure or any other issues.

> In case the Kafka connection is not available the message might be lost.
 
Is there any way not to lose the message? for example, roll back the message to VerneMQ or retry again and again up to success.

**Comment by Minipada** [comment]
I came here looking for the same info @AblEdge . I'm dealing with machines so this is important.
Could you answer your question? Or did you write your own "forwarder"?

**Comment by AblEdge** [comment]
not yet unfortunately.
@Minipada

**Comment by crisrise** [comment]
My view on this is that ordering, queing and message persistance are not something that you need to ask to an mqtt broker, this is my reason to have kafka in place in the system. Different is to cope with eventual vmq_kafka failures, imprving reliability in those cases.

**Comment by AblEdge** [comment]
I think it makes sense.
@crisrise
