### ISSUE TITLE
Is possible to send mqtt topic to kafka topic with same name?

### ISSUE THREAD

**Issue by giaptx** [crisrise/vmq_kafka#2]
Hi @crisrise, 

I wonder if we can send each mqtt topic to each kafka topic instead of send all mqtt topic to only one kafka topic?

Example:
```
mqtt/topic1 ->  kafka:topic1
mqtt/topic2 ->  kafka:topic2
```
Thanks

**Comment by crisrise** [comment]
Hi @giaptx I think that topic management in kafka and in mqtt follow different strategies. While topic in mqtt are, in principle, almost completely free in kafka the partition/topic needs to be planned in advance. 
I think that maybe you are suggesting it might be useful to have static mapping between some mqtt topic subtrees and a set of kafka topics, something like this:
```
mqtt/topic1/# ->  kafka:topic1
mqtt/topic2/# ->  kafka:topic2
```
Does this make sense for you?

**Comment by giaptx** [comment]
Thank you very much to help me understand. That is so clarify
